functionName: ply_keysh
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/klonoa-empire-of-dreams/build/src/m4a.o
asm: |
  	non_word_aligned_thumb_func_start ply_keysh
  ply_keysh: @ 08051392
  	ldr r0, [r1, #0x40]
  	ldrb r2, [r0, #0x00]
  	adds r0, r1, #0x0
  	adds r0, #0x24
  	strb r2, [r0, #0x00]
  	ldr r0, [r1, #0x40]
  	adds r0, #0x01
  	str r0, [r1, #0x40]
  	bx lr
  	lsls r0, r0, #0x00
