functionName: StrCpy
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/klonoa-empire-of-dreams/build/src/system.o
asm: |-
  	thumb_func_start StrCpy
  StrCpy: @ 08000460
  	ldrb r2, [r1, #0x00]
  	strb r2, [r0, #0x00]
  	adds r0, #0x01
  	adds r1, #0x01
  	cmp r2, #0x00
  	bne StrCpy
  	bx lr
  	lsls r0, r0, #0x00
