functionName: EntityDeathAnimation
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/klonoa-empire-of-dreams/build/src/code_1.o
asm: |
  	thumb_func_start EntityDeathAnimation
  EntityDeathAnimation: @ 0801DE44
  	push {r4, r5, r6, r7, lr}
  	mov r7, r8
  	push {r7}
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	ldr r7, _0801DEC0 @ =0x03002920
  	lsls r0, r5, #0x03
  	subs r0, r0, r5
  	lsls r0, r0, #0x02
  	adds r6, r0, r7
  	ldrb r0, [r6, #0x09]
  	subs r0, #0x01
  	movs r1, #0x00
  	mov r8, r1
  	strb r0, [r6, #0x09]
  	movs r4, #0xFF
  	lsls r0, r0, #0x18
  	lsrs r0, r0, #0x18
  	cmp r0, #0xFF
  	bne _0801DF3E
  	movs r0, #0x19
  	strb r0, [r6, #0x09]
  	ldrb r2, [r6, #0x08]
  	cmp r2, #0x05
  	bhi _0801DE94
  	ldr r0, _0801DEC4 @ =0x0300528C
  	ldrb r0, [r0, #0x00]
  	subs r0, r5, r0
  	lsls r1, r0, #0x03
  	subs r1, r1, r0
  	lsls r1, r1, #0x02
  	adds r1, r1, r7
  	ldrh r0, [r1, #0x00]
  	ldrh r1, [r1, #0x02]
  	adds r2, #0x0C
  	lsls r2, r2, #0x18
  	lsrs r2, r2, #0x18
  	movs r3, #0x00
  	bl SpawnEntityAtPosition
  _0801DE94:
  	ldrb r0, [r6, #0x08]
  	subs r0, #0x01
  	strb r0, [r6, #0x08]
  	ands r0, r4
  	cmp r0, #0x00
  	bne _0801DEC8
  	ldr r0, _0801DEC4 @ =0x0300528C
  	ldrb r3, [r0, #0x00]
  	subs r3, r5, r3
  	lsls r1, r3, #0x03
  	subs r1, r1, r3
  	lsls r1, r1, #0x02
  	adds r1, r1, r7
  	ldrh r0, [r1, #0x00]
  	ldrh r1, [r1, #0x02]
  	lsls r3, r3, #0x18
  	lsrs r3, r3, #0x18
  	movs r2, #0x02
  	bl SpawnEntityAtPosition
  	b _0801DF3E
  	lsls r0, r0, #0x00
  _0801DEC0: .4byte 0x03002920
  _0801DEC4: .4byte 0x0300528C
  _0801DEC8:
  	movs r0, #0x56
  	bl m4aSongNumStart
  	ldrb r0, [r6, #0x08]
  	cmp r0, #0x09
  	bls _0801DF02
  	ldr r2, _0801DFBC @ =0x0300528C
  	ldrb r1, [r2, #0x00]
  	adds r1, r5, r1
  	lsls r0, r1, #0x03
  	subs r0, r0, r1
  	lsls r0, r0, #0x02
  	adds r0, r0, r7
  	mov r1, r8
  	strb r1, [r0, #0x0F]
  	ldrb r4, [r2, #0x00]
  	adds r4, r5, r4
  	lsls r4, r4, #0x18
  	lsrs r4, r4, #0x18
  	ldrb r0, [r6, #0x08]
  	movs r1, #0x0A
  	bl FUN_08051a0c
  	adds r1, r0, #0x0
  	lsls r1, r1, #0x18
  	lsrs r1, r1, #0x18
  	adds r0, r4, #0x0
  	bl LoadSpriteFrame
  _0801DF02:
  	ldrb r0, [r6, #0x08]
  	movs r1, #0x0A
  	bl FUN_08051a84
  	adds r1, r0, #0x0
  	lsls r1, r1, #0x18
  	lsrs r1, r1, #0x18
  	adds r0, r5, #0x0
  	bl LoadSpriteFrame
  	ldrb r0, [r6, #0x08]
  	cmp r0, #0x09
  	bne _0801DF3E
  	ldr r2, _0801DFBC @ =0x0300528C
  	ldrb r1, [r2, #0x00]
  	adds r1, r5, r1
  	lsls r0, r1, #0x03
  	subs r0, r0, r1
  	lsls r0, r0, #0x02
  	adds r0, r0, r7
  	movs r1, #0x1C
  	strb r1, [r0, #0x0F]
  	ldrb r1, [r2, #0x00]
  	adds r1, r5, r1
  	lsls r0, r1, #0x03
  	subs r0, r0, r1
  	lsls r0, r0, #0x02
  	adds r0, r0, r7
  	mov r1, r8
  	strb r1, [r0, #0x10]
  _0801DF3E:
  	ldr r3, _0801DFC0 @ =0x03002920
  	lsls r0, r5, #0x03
  	subs r0, r0, r5
  	lsls r0, r0, #0x02
  	adds r4, r0, r3
  	ldr r6, _0801DFBC @ =0x0300528C
  	ldrb r1, [r6, #0x00]
  	subs r1, r5, r1
  	lsls r0, r1, #0x03
  	subs r0, r0, r1
  	lsls r0, r0, #0x02
  	adds r0, r0, r3
  	ldrh r0, [r0, #0x00]
  	strh r0, [r4, #0x00]
  	ldrb r1, [r6, #0x00]
  	subs r1, r5, r1
  	lsls r0, r1, #0x03
  	subs r0, r0, r1
  	lsls r0, r0, #0x02
  	adds r0, r0, r3
  	ldrh r0, [r0, #0x02]
  	subs r0, #0x20
  	strh r0, [r4, #0x02]
  	ldrb r0, [r4, #0x08]
  	cmp r0, #0x09
  	bls _0801DFB0
  	ldrb r2, [r6, #0x00]
  	adds r0, r5, r2
  	lsls r1, r0, #0x03
  	subs r1, r1, r0
  	lsls r1, r1, #0x02
  	adds r1, r1, r3
  	subs r2, r5, r2
  	lsls r0, r2, #0x03
  	subs r0, r0, r2
  	lsls r0, r0, #0x02
  	adds r0, r0, r3
  	ldrh r0, [r0, #0x00]
  	subs r0, #0x03
  	strh r0, [r1, #0x00]
  	ldrb r2, [r6, #0x00]
  	adds r0, r5, r2
  	lsls r1, r0, #0x03
  	subs r1, r1, r0
  	lsls r1, r1, #0x02
  	adds r1, r1, r3
  	subs r2, r5, r2
  	lsls r0, r2, #0x03
  	subs r0, r0, r2
  	lsls r0, r0, #0x02
  	adds r0, r0, r3
  	ldrh r0, [r0, #0x02]
  	subs r0, #0x20
  	strh r0, [r1, #0x02]
  	ldrh r0, [r4, #0x00]
  	adds r0, #0x03
  	strh r0, [r4, #0x00]
  _0801DFB0:
  	pop {r3}
  	mov r8, r3
  	pop {r4, r5, r6, r7}
  	pop {r0}
  	bx r0
  	lsls r0, r0, #0x00
  _0801DFBC: .4byte 0x0300528C
  _0801DFC0: .4byte 0x03002920
